---
- name: Store Passwords
  ansible.builtin.include_tasks: store_passwd.yml

- name: Install APT packages
  ansible.builtin.apt:
    name: "{{ buildbot_worker_apt_packages }}"
    state: latest
    update_cache: true
    cache_valid_time: 86400

- name: Install PIP packages
  ansible.builtin.pip:
    name: '{{ buildbot_worker_pip_packages }}'
    break_system_packages: true
    extra_args: "--ignore-installed"

- name: Install PIP buildbot worker
  ansible.builtin.pip:
    name: "buildbot-worker"
    version: "{{ buildbot_version }}"
    break_system_packages: true
    extra_args: "--ignore-installed"

- name: User
  ansible.builtin.user:
    name: '{{ buildbot_worker_user }}'
    comment: 'Dedicated user to run the buildbot worker'
    shell: '/bin/bash'

- name: Folder
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    owner: '{{ buildbot_worker_user }}'
    group: '{{ buildbot_worker_user }}'
    mode: "755"
  with_items:
    - '{{ buildbot_worker_basedir }}'
    - '{{ buildbot_worker_prepare_dir }}'

- name: Create
  ansible.builtin.command: >
    buildbot-worker create-worker {{ buildbot_worker_basedir }}
    {{ buildbot_worker_master_host }}:{{ buildbot_worker_master_port }}
    {{ buildbot_worker_name }} {{ generated_worker_password }}
  become: true
  become_user: '{{ buildbot_worker_user }}'
  args:
    creates: '{{ buildbot_worker_basedir }}/buildbot.tac'
  notify: Restart buildbot worker

- name: SystemD Unit File
  ansible.builtin.template:
    src: buildbot-worker.service.j2
    dest: /etc/systemd/system/buildbot-worker.service
    mode: "644"

- name: Admin
  ansible.builtin.copy:
    content: '{{ buildbot_worker_admin }}'
    dest: '{{ buildbot_worker_basedir }}/info/admin'
    mode: "644"

- name: Description
  ansible.builtin.copy:
    content: "{{ buildbot_worker_description }}"
    dest: '{{ buildbot_worker_basedir }}/info/host'
    mode: "644"
    force: false # note: file is finished in worker/configure task

- name: Export Facts
  ansible.builtin.set_fact:
    buildbot_master_host: '{{ buildbot_master_host }}'
    buildbot_worker_name: '{{ buildbot_worker_name }}'
    buildbot_worker_user: '{{ buildbot_worker_user }}'
    buildbot_worker_shell: '{{ buildbot_worker_shell }}'
    buildbot_worker_basedir: '{{ buildbot_worker_basedir }}'
    buildbot_worker_prepare_dir: '{{ buildbot_worker_prepare_dir }}'
    buildbot_worker_platforms: '{{ buildbot_worker_platforms }}'
  tags: always
