---
- name: Generate Worker Password
  ansible.builtin.set_fact:
    generated_worker_password: >-
      {{ (((ansible_local | default({})).buildbot | default({})).facts | default({})).password | default(buildbot_worker_password) }}
  tags: [always]

- name: Store_facts | facts directory
  ansible.builtin.file:
    path: "{{ ansible_facts_path }}"
    state: directory
    recurse: true

- name: Store_facts | generated worker password
  community.general.ini_file:
    dest: "{{ ansible_facts_path }}/buildbot.fact"
    create: true
    section: "facts"
    option: "password"
    value: "{{ generated_worker_password }}"
    mode: "644"
  when: generated_worker_password != ''

- name: Store_facts | re-read
  ansible.builtin.setup:
    filter: ansible_local
