---
- name: reconfigure buildbot master
  service:
    name: buildbot
    state: reloaded
  become: yes
  delegate_to: '{{ buildbot_master_host }}'

- name: restart buildbot worker
  service:
    name: buildbot-worker
    state: restarted
