---
- name: Reconfigure buildbot master
  ansible.builtin.set_fact:
    buildbot_master_reload: true
  delegate_to: '{{ buildbot_master_host }}'
  delegate_facts: true

- name: Restart buildbot worker
  ansible.builtin.set_fact:
    buildbot_worker_restart: true
