---
- name: Flush Handlers
  ansible.builtin.meta: flush_handlers

- name: Restart buildbot master
  ansible.builtin.shell: |
    set -e
    if [ -n "$(ls -A {{ buildbot_master_workers_path }})" -a -n "$(ls -A {{ buildbot_master_projects_path }})" ]; then
      buildbot restart {{ buildbot_master_basedir }} || buildbot start {{ buildbot_master_basedir }}
    else
      echo "Not starting master buildbot, because either no workers or no projects configured!" 1>&2
      exit 1
    fi
  changed_when: true
  become: true
  become_user: '{{ buildbot_master_user }}'
  when: buildbot_master_restart | default(false)

- name: Reconfigure buildbot master
  ansible.builtin.shell: |
    set -e
    if [ -n "$(ls -A {{ buildbot_master_workers_path }})" -a -n "$(ls -A {{ buildbot_master_projects_path }})" ]; then
      buildbot reconfig {{ buildbot_master_basedir }} || buildbot start {{ buildbot_master_basedir }}
    fi
  become: true
  become_user: '{{ buildbot_master_user }}'
  changed_when: true
  when: buildbot_master_reload | default(false) and not (buildbot_master_restart | default(false))

- name: Reset facts
  ansible.builtin.set_fact:
    buildbot_master_reload: false
    buildbot_master_restart: false
