---
- name: Flush Handlers
  ansible.builtin.meta: flush_handlers

- name: Enable Worker Service
  ansible.builtin.service:
    name: buildbot-worker
    enabled: true
    state: "{{ 'restarted' if (buildbot_worker_restart | default(false)) else 'started' }}"
  retries: 2 # note: first start might fail
  delay: 1
