---
- meta: flush_handlers

- name: Enable Worker Service
  service:
    name: buildbot-worker
    enabled: yes
    state: "{{ 'restarted' if (buildbot_worker_restart | default(False)) else 'started' }}"
