---
- meta: flush_handlers

- name: Restart Worker
  service:
    name: buildbot-worker
    state: restarted
  when: buildbot_worker_restart | default(False)

- name: Start Worker
  service:
    name: buildbot-worker
    enabled: yes