---
- name: reconfigure buildbot master
  service:
    name: buildbot
    state: reloaded
  become: yes
  delegate_to: '{{ buildbot_master_host }}'

- name: restart buildbot winworker
  win_file:
    path: "{{ buildbot_worker_basedir }}\\restart.txt"
    state: touch
