---
- name: reconfigure buildbot master
  set_fact:
    buildbot_master_reload: true
  delegate_to: '{{ buildbot_master_host }}'

- name: restart buildbot winworker
  win_service:
    name: BuildBot
    state: restarted
