---
- name: config
  template:
    src: 'project.yml.j2'
    dest: '{{ buildbot_master_projects_path }}/{{ project_name }}.yml'
  become: yes
  become_user: '{{ buildbot_master_user }}'
  notify:
  - reconfigure buildbot master
