---
- name: install APT packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
    cache_valid_time: 86400
  with_items: "{{ buildbot_master_apt_packages }}"

- name: update pip
  pip:
    name: pip
    state: latest

- name: Install PIP packages
  pip:
    name: "{{ item }}"
  with_items: "{{ buildbot_master_pip_packages }}"

- name: Install PIP buildbot
  pip:
    name: "{{ item }}"
    version: "{{ buildbot_version }}"
  notify:
  - restart buildbot masters
  with_items:
  - buildbot[tls] # explicitly set the TLS option
  - buildbot-www
  - buildbot-waterfall-view
  - buildbot-console-view

- name: Path
  file:
    path: "{{ buildbot_master_path }}"
    state: directory

- name: Store Facts
  set_fact:
    buildbot_master_path: '{{ buildbot_master_path }}'
  tags: [always]
