---

- name: enable buildbot master
  service:
    name: buildbot
    enabled: yes

- name: reload buildbot master
  service:
    name: buildbot
    state: reloaded
  when: buildbot_master_reload | default(False)

- name: restart buildbot master
  service:
    name: buildbot
    state: restarted
  when: buildbot_master_restart | default(False)
