---
- name: Enable buildbot master
  ansible.builtin.service:
    name: buildbot
    enabled: true

- name: Reload buildbot master
  ansible.builtin.service:
    name: buildbot
    state: reloaded
  when: buildbot_master_reload | default(false)

- name: Restart buildbot master
  ansible.builtin.service:
    name: buildbot
    state: restarted
  when: buildbot_master_restart | default(false)
